---
- name: Configure NAS server
  hosts: nas_server
  become: true

  handlers:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true

    - name: Restart SMB
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Load vars
      ansible.builtin.include_vars: config.yaml

    - name: Load vault
      ansible.builtin.include_vars: vault.yaml

    - name: Add contrib repository
      ansible.builtin.deb822_repository:
        name: debian
        types: deb
        uris: http://deb.debian.org/debian
        suites: trixie
        components:
          - main
          - contrib
      notify: Update apt repos

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install samba
      ansible.builtin.apt:
        name:
          - samba
        state: present

    - name: Make sure samba is started and enabled
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true

    - name: Install ZFS
      ansible.builtin.apt:
        name:
          - linux-headers-amd64
          - zfsutils-linux
          - zfs-dkms
          - zfs-zed
        state: present

    - name: Add ZFS module
      community.general.modprobe:
        name: zfs
        state: present

    - name: Create ZFS pools
      ansible.builtin.command:
        cmd: zpool create {{ item.name }} {{ item.members }} -f
        creates: /{{ item.name }}
      loop: "{{ zfs_pools }}"

    - name: Create filesystems
      community.general.zfs:
        name: "{{ item.name }}"
        state: present
        extra_zfs_properties:
          compression: lz4
      loop: "{{ zfs_zvols }}"

    - name: Configure samba
      ansible.builtin.template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart SMB

    - name: Configure privilages for samba shares
      ansible.builtin.file:
        path: "/{{ item.name }}"
        state: directory
        owner: "{{ smb_user }}"
        group: "root"
        mode: "0755"
      loop: "{{ zfs_zvols }}"

    # https://gist.github.com/cmsj/5557c45ca5fa4779e81394105be204e1
    # This task will run only if user doesn't exists.
    # Changing password won't work.
    - name: Fetch current smbpasswd users
      ansible.builtin.command: /usr/bin/pdbedit -L
      register: pdb_users
      changed_when: false

    - name: Set Samba password for smbuser
      ansible.builtin.command:
        cmd: /usr/bin/smbpasswd -s -a {{ ansible_user }}
        stdin: |
          {{ smbuser_password }}
      when: pdb_users.stdout.find(ansible_user) == -1
      changed_when: false  # Only to satisfy ansible lint
